/**
 * contains actions constants
 */


/**
 * Employee
 */
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const GET_EMPLOYEE_LOGIN = "GET_EMPLOYEE_LOGIN";
export const GET_ALL_EMPLOYEE = "GET_ALL_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

/**
 * Personalinfo
 */
export const GET_ALL_PERSONALINFO = "GET_ALL_PERSONALINFO";
export const GET_PERSONALINFO_BY_ID = "GET_PERSONALINFO_BY_ID"
export const CREATE_PERSONALINFO = "CREATE_PERSONALINFO";
export const UPDATE_PERSONALINFO = "UPDATE_PERSONALINFO";
export const DELETE_PERSONALINFO = "DELETE_PERSONALINFO";

/**
 * Contactinfo
 */
export const GET_ALL_CONTACTINFO = "GET_ALL_CONTACTINFO";
export const GET_CONTACTINFO_BY_ID = "GET_CONTACTINFO_BY_ID"
export const CREATE_CONTACTINFO = "CREATE_CONTACTINFO";
export const UPDATE_CONTACTINFO = "UPDATE_CONTACTINFO";
export const DELETE_CONTACTINFO = "DELETE_CONTACTINFO";

/**
 * Leaveinfo
 */
export const GET_LEAVEINFO_BY_ID = "GET_LEAVEINFO_BY_ID"
export const CREATE_LEAVEINFO = "CREATE_LEAVEINFO";
export const UPDATE_LEAVEINFO = "UPDATE_LEAVEINFO";
export const DELETE_LEAVEINFO = "DELETE_LEAVEINFO";

/**
 * Skillinfo
 */
export const GET_SKILLINFO_BY_ID = "GET_SKILLINFO_BY_ID"
export const CREATE_SKILLINFO = "CREATE_SKILLINFO";
export const UPDATE_SKILLINFO = "UPDATE_SKILLINFO";
export const DELETE_SKILLINFO = "DELETE_SKILLINFO";

/**
 * Directory
 */
export const GET_DIRECTORY = "GET_DIRECTORY";